### ISSUE TITLE
Ошибка разархивирования

### ISSUE THREAD

**Issue by PopovEV** [IvanSafonov/sdeploy#1]
Если на целевой машине установлено время в прошлом, то при разархивировании tar будет ругаться. 

Extracting package on the remote host...
stderr: tar: Removing leading `/' from member names
tar: .: time stamp 2015-09-02 14:41:06 is 55.905364711 s in the future
tar: linuxcash/cash/drivers/libfrenvd.so: time stamp 2015-09-02 14:41:06 is 55.903531237 s in the future
tar: linuxcash: time stamp 2015-09-02 14:41:06 is 55.881518653 s in the future

**Comment by IvanSafonov** [comment]
fixed
